$schema: https://raw.githubusercontent.com/zokugun/artifact/v0.12.0/schemas/v4/install.json
artifacts:
  "@daiyam/artifact-lang-js":
    version: 0.14.7
    requires:
      - "20"
  "@daiyam/artifact-lang-ts":
    version: 0.10.6
    update:
      .xo-config.json:
        if_missing: skip
      tsconfig.base.json:
        if_missing: skip
      tsconfig.json:
        if_exists: skip
  "@daiyam/artifact-vsx-ts":
    version: 0.11.17
    update:
      .vscodeignore:
        if_exists: skip
      .github/**:
        if_exists: skip
      src/**:
        if_missing: skip
  "@daiyam/artifact-test-vitest-ts":
    version: 0.5.8
    features:
      - test
