name: Preview

on:
  workflow_dispatch: {}

permissions:
  contents: write   # Release

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get Version
        run: |
          # Get the latest tag
          LATEST_TAG=$(git tag --sort=-v:refname | head -n1)

          if [ -z "$LATEST_TAG" ]; then
            echo "No tags found in the repository"
            exit 1
          fi

          echo "VERSION=$LATEST_TAG" >> $GITHUB_ENV
          echo "Using version: $LATEST_TAG"

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          package-manager-cache: false

      # - name: Update package.json
      #   run: |
      #     TIME_PATCH="$(date +%-y)$(printf "%04d" $(($(date +%-j) * 24 + $(date +%-H))))"
      #     VERSION="${VERSION#v}-$TIME_PATCH"
      #     echo "Using version: $VERSION"

      #     jq --arg version "$VERSION" '.version = $version | .preview = true' package.json > package.json.tmp
      #     mv package.json.tmp package.json

      #     jq -r '"version: \(.version)\npreview: \(.preview)"' package.json

      #     echo "RELEASE_TAG=v$VERSION" >> $GITHUB_ENV
      - name: Update package.json
        run: |
          jq '.preview = true' package.json > package.json.tmp
          mv package.json.tmp package.json

          npx bumpp --no-push prerelease --yes --current-version "$VERSION" || true

          jq -r '"version: \(.version)\npreview: \(.preview)"' package.json

          VERSION="$(jq -r .version package.json)"

          echo "RELEASE_TAG=v$VERSION" >> $GITHUB_ENV

      - name: Build
        run: |
          npm ci

          npm run package

          VSIX_NAME=$(ls *.vsix)
          CHECKSUM=$(sha256sum $VSIX_NAME | cut -d ' ' -f 1)

          echo "VSIX_NAME=$VSIX_NAME" >> $GITHUB_ENV
          echo "CHECKSUM=$CHECKSUM" >> $GITHUB_ENV
          echo "$CHECKSUM" > "$VSIX_NAME.sha256"

      - name: Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: |
            ${{ env.VSIX_NAME }}
            ${{ env.VSIX_NAME }}.sha256
          name: ${{ env.RELEASE_TAG }}
          tag_name: ${{ env.RELEASE_TAG }}
          prerelease: true
          body: |
            Release ${{ env.RELEASE_TAG }}

            ## What's Changed

            ## Installation
            1. [Download the .vsix file](${{ github.server_url }}/${{ github.repository }}/releases/download/${{ env.VERSION }}/${{ env.VSIX_NAME }})
            2. In your editor, open the Command Palette (<kbd>Meta</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
            3. Type `Install from VSIX` and select the downloaded file

            ## Checksum (SHA-256)
            ```
            ${{ env.CHECKSUM }}
            ```
